### ISSUE TITLE
Create DNF Unique Navs for General Use

### ISSUE THREAD

**Issue by RelycX** [RelycX/Haybale#1]
1. Haven - get to Haven
2. Haven Buffs - collect buffs from Curmudgeon and +Health - get landblock
3. Portal Room in Abandoned Mines (Subway)
4. Portal Room in Jungle Sub
5. Frozen Valley Cabins (from Jungle Sub Portal Room) - get landcell
6. Go to MR - check for summoning gem in inventory
7. Go to VoD
8. Collect MR KT's (from MR drop)
9. Collect VoD KT's (from VoD drop)
10.  2 Routes for Gromnie Use  - check for Gromnie in inventory, summon it, check for gromnie within range, give it items for:    Asheron's Castle, Temple of Forgetfullness

DNF Tab on Chaos Helper?

**Comment by bmease** [comment]
OMG! these are amazing ideas!!! We so need a DNF tab on Chaos Helper!

**Comment by RelycX** [comment]
This issue has been split into multiple issues for smaller pieces to bite off.
